APS-2727, Added new release notes for NS to GW
bcgov/aps-infra-platform pull request #76
Opened 2024-08-07 19:41 UTC by SateeshFW

Added release notes for Sept release and also updated the index page with the new release page

2024-08-07 23:09 UTC, timng-bcgov reviewed
I suggest using [Markdownlint ](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to lint & wrap any lines that are longer than 80 characters.

2024-08-07 23:09 UTC, timng-bcgov commented on documentation/reference/releases/2024-sept-3.0.0.md
> +  * This page provides a basic introduction and instructions for the new Quick Start process for API providers.
```suggestion
  * This page provides a basic introduction and instructions for the new Quick Start tutorial for API providers.
```

2024-08-07 23:09 UTC, timng-bcgov commented on documentation/reference/releases/2024-sept-3.0.0.md
> +  * The new Quick Start tutorial offers a faster and simpler option to begin with before progressing to the [Protect an API with Client Credential Flow](https://developer.gov.bc.ca/docs/default/compo
```suggestion
  * The new Quick Start tutorial offers a simpler option to begin with before progressing to the [Protect an API with Client Credential Flow](https://developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs/tutorials/protect-client-cred/) tutorial (previously called Quick Start). 
  * The revised Quick Start tutorial utilizes a new `quick-start` configuration template.
```

2024-08-07 23:09 UTC, timng-bcgov commented on documentation/reference/releases/2024-sept-3.0.0.md
> +* `--gateway-id` and `--display-name` can be used to specify these attributes.
```suggestion
  * The `--gateway-id` and `--display-name` flags can be used to specify these attributes.
```

2024-08-08 16:55 UTC, rustyjux requested changes
A few suggested changes to provide more or more accurate context in the intro sentence, and reducing some unnecessary details for end users. Hopefully my comments line up still - Tim pushed some line wrapping changes while I was mid-review.

When it comes to writing communication to send out to users, I think we will want to also include a 'What do I need to do' section which reinforces that users don't need to do anything and that all existing Namespaces are preserved and now called Gateways.

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +The API Services Portal has been updated with enhancements in the existing features.
Adding a little high level summary.
```suggestion
The API Services Portal has been updated with enhancements to improve the API provider experience. 
The core of these updates is the renaming of 'Namespaces' to 'Gateways' throughout the the API Services Portal.
```

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +* Capability to create a gateway directly from the command line.
```suggestion
```
This is not new.

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +* The `--gateway-id` and `--display-name` flags can be used to specify these attributes.
```suggestion
```
Too much detail for here.

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +* Improvements to error reporting for Gateway Service publication (`gwa apply` and `gwa publish-gateway`). Additional error messaging is shown by default to support troubleshooting.
```suggestion
* Improvements to error reporting for Gateway Service publication (`gwa apply` and `gwa publish-gateway`) to support troubleshooting.
```

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +* Improvements to Gateway Service configuration creation using templates (`gwa generate-config`). Gateway `service` and `route` names are validated for availability during configuration creation.
```suggestion
* Improvements to Gateway Service configuration creation using templates (`gwa generate-config`). 
  * Gateway `service` and `route` names are validated for availability during configuration creation.
```

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +* Templates for implementing common authorization patterns on the API Gateway.
```suggestion
```
This is not new. There is a new template `quick-start` but it's captured above in Portal.

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +Gateway Command Line Interface Version 3 (GWA-CLI V3.0.1) is a new and enhanced tool for configuring your API Gateway settings. Key improvements include:
The supposed full name for the tool is 'gateway admin' but we never use that, only `gwa` - which is 'gwah' or 'gee-double-you-eh'
```suggestion
The `gwa` command line tool has been updated to support the changes to the API Services Portal, along with additional improvements to support Gateway Service configuration.
```

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +## GWA-CLI V3
As per https://dev.developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs/contribute/style-guide/#use-code-style-for-gwa-command-line-tool. And then I dropped to `v` to be in line with the format for API Services Portal. Changing to v on both would also be reasonable.
```suggestion
## `gwa` CLI 3.0.1
```

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +  * Added breadcrumbs on Gateway management pages.
```suggestion
```
Not necessary

2024-08-08 16:55 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +
```suggestion

!!! note "New Gateway creation"
    Whereas previously it was possible to create a new Namespace via the `gwa` CLI or API Services Portal web interface, it is now _only_ possible to create Gateways using `gwa`.

```

2024-08-08 19:29 UTC, rustyjux commented on documentation/reference/releases/2024-sept-3.0.0.md
> +Gageways using `gwa`.
This formatting will not work and also breaks with the style guide. Same with the changes you made to the `!!! note` line. Please use the changes I provided before as is and review the style guide for usage on callouts https://dev.developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs/contribute/style-guide/#callouts
Previewing locally will reveal these issues or if syntax is correct.

You also have a typo and wrote 'Gageways'

2024-08-09 18:41 UTC, rustyjux approved these changes

2024-08-09 19:07 UTC, merged